### ISSUE TITLE
what does sentimental_clauses.pkl do?

### ISSUE THREAD

**Issue by yuto3o** [zhoucz97/ECPE-MM-R#3]
In main.py, I find that https://github.com/zhoucz97/ECPE-MM-R/blob/1f6698116e9222e24816297b1c9f80c4bf5112f9/main.py#L52

It seems that you use a sentiment dictionary to filter out the results. But when I want to go further, no more details are mentioned in your paper. Could you give me some help?

**Comment by zhoucz97** [comment]
The sentiment dictionary used in our paper comes from the ACL paper "Effective Inter-Clause Modeling for End-to-End Emotion-Cause Pair Extraction". It is not our innovation point, so we did not mention it in our paper. 
This dictionary is important because it can improve the recall of Emotion Extraction, **Please see the paper "Effective Inter-Clause Modeling for End-to-End Emotion-Cause Pair Extraction" for more details.**

**Comment by yuto3o** [comment]
Thank you for your quick response. 

I found an interesting result (in the paper `A Consistent Dual-MRC Framework for Emotion-Cause Pair Extraction`) that Emotion Filtering (with sentiment dictionary) improves ECPE F1 with ~5 points.

Do you observe the similar improvement?

**Comment by zhoucz97** [comment]
Yeah, in our work, the dictionary is also important, improving f1 with about 3~4 points (a long time, I can't remember exactly)....
The reason is that the emotion words in emotional utterances of ECPE dataset is large overlap with the words in emotional dictionary.

**Comment by yuto3o** [comment]
Thanks :)
